version: "3.8"

services:
    notification-service:
        container_name: notification-service
        image: notification-service
        build: .
        ports:
            - 4500:3000
        networks:
            - microservice

        env_file:
            - .env
        environment:
            - RABBITMQ_URL=${RABBITMQ_URL}
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run dev

networks:
    microservice:
        external: true
        name: microservice
