apiVersion: apps/v1
kind: Deployment
metadata:
    name: product-service-deployment
    labels:
        app: product-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: product-service-pod
    template:
        metadata:
            labels:
                app: product-service-pod
        spec:
            containers:
                - name: product-service-container
                  image: brymat24/product-service:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: DIRECT_URL
                        valueFrom:
                            secretKeyRef:
                                name: product-service-secret
                                key: DIRECT_URL
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: product-service-secret
                                key: DATABASE_URL
                      - name: PAGE_SIZE
                        valueFrom:
                            secretKeyRef:
                                name: product-service-secret
                                key: PAGE_SIZE
                      - name: RABBITMQ_URL
                        valueFrom:
                            secretKeyRef:
                                name: product-service-secret
                                key: RABBITMQ_URL
            restartPolicy: Always
