apiVersion: v1
kind: Service
metadata:
    name: product-service-svc
spec:
    selector:
        app: product-service-pod
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: ClusterIP
