apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-service-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: order-service-pod
    template:
        metadata:
            labels:
                app: order-service-pod
        spec:
            containers:
                - name: order-service-container
                  image: brymat24/order-service:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: DATABASE_URL
                      - name: DIRECT_URL
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: DIRECT_URL
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: JWT_SECRET
                      - name: STRIPE_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: STRIPE_API_KEY
                      - name: STRIPE_WEBHOOK_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: STRIPE_WEBHOOK_SECRET
                      - name: CLIENT_URL
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: CLIENT_URL
                      - name: PRODUCT_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: order-service-configmap
                                key: PRODUCT_SERVER
                      - name: CART_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: order-service-configmap
                                key: CART_SERVER
                      - name: RABBITMQ_URL
                        valueFrom:
                            secretKeyRef:
                                name: order-service-secret
                                key: RABBITMQ_URL
            restartPolicy: Always
