version: "3.8"

services:
    product-service:
        container_name: product-service
        image: product-service
        build: .
        ports:
            - 5500:3000
        networks:
            - microservice
        environment:
            - DATABASE_URL=postgresql://postgres.ngbskfjaxhiiadfuzpfb:4coD5IOcFW6UFZV1@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
            - DIRECT_URL=postgresql://postgres.ngbskfjaxhiiadfuzpfb:4coD5IOcFW6UFZV1@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        command: ["npm", "run", "dev"]

networks:
    microservice:
        driver: bridge
