version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3.13.4-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/data
        networks:
            - microservice

volumes:
    rabbitmq_data:

networks:
    microservice:
        external: true
        name: microservice
