apiVersion: apps/v1
kind: Deployment
metadata:
    name: cart-service-deployment
    namespace: default
spec:
    selector:
        matchLabels:
            app: cart-service-pod
    replicas: 2
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: cart-service-pod
        spec:
            containers:
                - name: cart-service-container
                  image: brymat24/cart-service:latest
                  env:
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: cart-service-secret
                                key: JWT_SECRET
                      - name: PRODUCT_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: cart-service-configmap
                                key: PRODUCT_SERVER
                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: cart-service-configmap
                                key: REDIS_HOST
                  ports:
                      - containerPort: 3000
            restartPolicy: Always
