apiVersion: v1
kind: Service
metadata:
    name: cart-service-svc
    namespace: default
spec:
    selector:
        app: cart-service-pod
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
