version: "3.8"

services:
    user-service:
        container_name: user-service
        build: .
        ports:
            - "4000:3000"
        networks:
            - microservice
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        env_file:
            - .env

networks:
    microservice:
        driver: bridge
